gems:
  - jekyll-sitemap
encoding: utf-8
keywords: skeletal,animation,library,engine,game,3d,c++,cpp,cplusplus,open,source,mit,skeleton,bone,joint,character,blending,skinning,ik,load,import,fbx,gltf,collada,dae,obj,directx,opengl
collections:
  samples:
    display_name: Samples
    output: true
    permalink: /:collection/:path/
    order: 2
  documentation:
    display_name: Documentation
    output: true
    order: 1
    permalink: /:collection/:path/
  proto:
    display_name: Proto
    output: true
    order: -1
    permalink: /:collection/:path
  
