gems:
  - jekyll-sitemap
encoding: utf-8
google-tracking-id: UA-35633955-2
keywords: open, source, animation, library, engine, game, 3d, c++, cpp, cplusplus, skeleton, skeletal, bone, joint, character, blending, load, import, fbx, collada, obj, directx, opengl
collections:
  samples:
    display_name: Samples
    output: true
    permalink: /:collection/:path/
  documentation:
    display_name: Documentation
    output: true
    permalink: /:collection/:path/
